### ISSUE TITLE
Errata: Puzzle 1 - Dance Partners

### ISSUE THREAD

**Issue by LarsOevlisen** [smpetersgithub/AdvancedSQLPuzzles#1]
The text for puzzle 1 states:

“Note there is a mismatch in the number of students, as one female student will be left without a dance partner. Please include this individual in your list as well.”

Shouldn’t this state “… as one male student will be left without …”?

**Comment by Teggy** [comment]
I was just about to submit that issue. ;-)  You are correct, Lars, I'd guess.

**Comment by smpetersgithub** [comment]
Thank you for pointing this out.  I've modified this puzzle to performing an audit on two shopping carts, as this is a better puzzle that showcases the use of a FULL OUTER JOIN.

I hope you enjoy the puzzles and let me know of any other errors that you see.
