### ISSUE TITLE
Does not fit to the assigment table

### ISSUE THREAD

**Issue by maximilian22x** [smpetersgithub/AdvancedSQLPuzzles#10]
https://github.com/smpetersgithub/AdvancedSQLPuzzles/blob/e081714f561f31ae59bf40a933ec33d2bbe2a05e/Advanced%20SQL%20Puzzles/Advanced%20SQL%20Puzzles%20DDL.sql#L401

**Comment by smpetersgithub** [comment]
This has been fixed in the DDL file and the Solutions file.  Thank You!
