### ISSUE TITLE
The expected output table is wrong in the pdf 

### ISSUE THREAD

**Issue by maximilian22x** [smpetersgithub/AdvancedSQLPuzzles#18]
https://github.com/smpetersgithub/AdvancedSQLPuzzles/blob/f7ade1b957e6559a6c0f5f31626f5a572e2504f5/Advanced%20SQL%20Puzzles/Advanced%20SQL%20Puzzles%20Solutions.sql#L928

**Comment by smpetersgithub** [comment]
Thank you!

I fixed the PDF and I also added a new solution using the MAX function.
