### ISSUE TITLE
Correction in Puzzle #21: Average Monthly Sales 

### ISSUE THREAD

**Issue by itsumarfarooq** [smpetersgithub/AdvancedSQLPuzzles#2]
It should be changed from this 

> Iowa would not show in the result set because Customer ID 3003 did
> not have an average monthly value over $100 in May 2018.

to this in the problem statement 

> Iowa would not show in the result set because Customer ID 4004 did
> not have an average monthly value over $100 in May 2018.

Simply change the CustomerID from 3003 to 4004. In May, 4004 has an average sales of 75 and 3003 doesn't even exist.

**Comment by smpetersgithub** [comment]
I have updated the PDF document and merged it into the repository.

Please contact me with any errors that you find.  Thank you!
