### ISSUE TITLE
Two minor errors in Advanced SQL Puzzles DDL.sql

### ISSUE THREAD

**Issue by jmadison222** [smpetersgithub/AdvancedSQLPuzzles#31]
Love this project!!!

In the file Advanced SQL Puzzles DDL.sql, there are two minor errors:

- Line 335 should be `/*` to start the comment rather than just `*`.
- Line 646 has an extra comma at the end.

Not sure if these cause issues in SQL Server, but when I run them on Snowflake, they do, and they're tricky to fix with sed, so hoping you can fix them in the source.

I have to make a bunch of other changes to work in Snowflake, but the syntax is distinct enough that it's not an issue.

Thanks!

**Comment by smpetersgithub** [comment]
Thank you!   I will merge these changes shortly.  Let me know if you find any other issues.

**Comment by smpetersgithub** [comment]
I have made the changes to the Advanced SQL Puzzles DDL.sql file.  The SQL Server script executes to completion without any errors.

Please don't hesitate to send me the SQL file containing the DDL statements for Snowflake, if you wish to do so.  I can include this in the repository for future developers.  You can email me from the contacts page of my WordPress site (advancedsqlpuzzles.com).

Thank you again!  If you spot anything else, please let me know.
