### ISSUE TITLE
No solution to puzzle 35

### ISSUE THREAD

**Issue by Palicho** [smpetersgithub/AdvancedSQLPuzzles#34]
Hey,
I really appreciated you work, but there is a missing solution to puzzle 35 in file named 'Advanced SQL Puzzles Solutions'.
Instead of solution there is alternative answer to to puzzle 34.

**Comment by smpetersgithub** [comment]
I've have committed the changes that resolve the issues for Puzzle #34 and #35.

For Puzzle #34, I've incorporated a new solution that demonstrates Morgan's Law.

For Puzzle #35, I've supplied a solution, plus I slightly modified the test data.  I will need to fix the PDF file later this week.

**Comment by smpetersgithub** [comment]
Closing Issue
