### ISSUE TITLE
Convert DDL to Snowflake - Not an issue any more, just some code others might benefit from.

### ISSUE THREAD

**Issue by jmadison222** [smpetersgithub/AdvancedSQLPuzzles#38]
Scott:

Love your product!  But forget this request.  Short version, I use Snowflake, and I need to make some tweaks to get it there, but I'm good.

For reference, here is what I run to get on Snowflake:

```
        #
        # Convert SQL Server to Snowflake.
        #
        sed -i 's/SET NOCOUNT ON;//g' puzz.sql     # Directive at the top.
        sed -i 's/\[/\"/g' puzz.sql                # Replace opening bracket.
        sed -i 's/\]/\"/g' puzz.sql                # Replace closing bracket.
        sed -i 's/, Year)/, "Year")/g' puzz.sql    # One more in the PK clause.
        sed -i 's/^GO$//g' puzz.sql                # SQL Server's "Go" command.
        sed -i 's/MONEY/DECIMAL(38,4)/g' puzz.sql  # Change MONEY to DECIMAL.
        sed -i 's/USE test;//g' puzz.sql           # Stay in one database.
        sed -i 's/MAX/4000/g' puzz.sql             # Really big string.

```

Thanks!

James

**Comment by jmadison222** [comment]
Ah, wait!  Never mind.  This already happens in a bunch of places that I replaced, but there are apparently a few new ones.  I'll just sed the script.

```
        sed -i 's/\[/\"/g' puzz.sql
        sed -i 's/\]/\"/g' puzz.sql

```
Easy enough.

Rock on!

James

**Comment by smpetersgithub** [comment]
Thanks for the email.

You are correct that I should not use reserved words for column names.  It’s something I've meant to change this.

Also, my box dimension puzzle answer is wrong.   The answer gives a solution if they have the same volume, but not the same dimensions.  I will need to update this as well.

Scott



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jmadison222** [comment]
That would be great if you did the column rename.  Also, I have a number of other observations for a number of questions around ambiguities and edge cases.  As the months and years go by, I can submit some to you if you want.  

Not trying to make work if this is just a hobby, etc.  But I study and work the problems carefully, so I'm happy to send along my thoughts on what might be good improvements.  Then you can do with them what you will.

Thanks!

James

**Comment by smpetersgithub** [comment]
Yes. Please share any findings.  Im always thankful to get the puzzles peer reviewed by other developers.

Scott

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
