### ISSUE TITLE
Title change and author credit in the Mandelbrot SQL file

### ISSUE THREAD

**Issue by Bilbottom** [smpetersgithub/AdvancedSQLPuzzles#41]
First off, great set of questions -- it's clear that you've put in a great deal of work to get these together, and it's very impressive!

I have two suggestions for your Mandelbrot Set recursion reference file:

https://github.com/smpetersgithub/AdvancedSQLPuzzles/blob/a69c9ef322860969f08a982b9fb89744d1b57cd7/Advanced%20SQL%20Puzzles/Recursion%20Examples/Mandelbrot%20Set%20Recursion.sql#L1-L10

1. The title still says `Sudoku` (on line 3) but I'm guessing this should be `Mandelbrot Set`
2. Please can you credit the original author somewhere in the header?

AFAIK, the SQL was originally authored by Graeme Job in 2008 -- one of the places that it was shared is on the following blog:

- https://thedailywtf.com/articles/stupid-coding-tricks-the-tsql-madlebrot

**Comment by smpetersgithub** [comment]
Thank you.  I will make the change and reference the article.  Please let me know of any other issues you find.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Bill ***@***.***>
Sent: Saturday, June 29, 2024 6:44:28 AM
To: smpetersgithub/AdvancedSQLPuzzles ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [smpetersgithub/AdvancedSQLPuzzles] Title change and author credit in the Mandelbrot SQL file (Issue #41)


First off, great set of questions -- it's clear that you've put in a great deal of work to get these together, and it's very impressive!

I have two suggestions for your Mandelbrot Set recursion reference file:

https://github.com/smpetersgithub/AdvancedSQLPuzzles/blob/a69c9ef322860969f08a982b9fb89744d1b57cd7/Advanced%20SQL%20Puzzles/Recursion%20Examples/Mandelbrot%20Set%20Recursion.sql#L1-L10

  1.  The title still says Sudoku (on line 3) but I'm guessing this should be Mandelbrot Set
  2.  Please can you credit the original author somewhere in the header?

AFAIK, the SQL was originally authored by Graeme Job in 2008 -- one of the places that it was shared is on the following blog:

  *   https://thedailywtf.com/articles/stupid-coding-tricks-the-tsql-madlebrot
