### ISSUE TITLE
Does not fit with assigment table. 

### ISSUE THREAD

**Issue by maximilian22x** [smpetersgithub/AdvancedSQLPuzzles#8]
https://github.com/smpetersgithub/AdvancedSQLPuzzles/blob/e081714f561f31ae59bf40a933ec33d2bbe2a05e/Advanced%20SQL%20Puzzles/Advanced%20SQL%20Puzzles%20Solutions.sql#L738

**Comment by smpetersgithub** [comment]
This has been fixed in both the DDL and the Solutions file.  Thank You!
